/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ContactConfirmFrame.java
 *
 * Created on 29-Nov-2009, 3:09:10 PM
 */

package Contacts;

import org.jdesktop.application.Action;

/**
 *
 * @author mrandell
 */
public class ContactConfirmPrompt extends javax.swing.JFrame {

    private String name;
    private ContactNetWrapper cn;

    public ContactConfirmPrompt(String n, ContactNetWrapper cnet) {
        initComponents();
        this.setDefaultCloseOperation(this.DO_NOTHING_ON_CLOSE);
        name = n;
        cn = cnet;
        qLabel.setText("Confirm " + n + " as a contact?");
    }

    @Action
    public void Confirm() {
        //cn.respond(true, name);        // TODO add your handling code here:
        this.dispose();
    }

    @Action
    public void Reject() {
        //cn.respond(false, name);
        this.dispose();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        qLabel = new javax.swing.JLabel();
        conButton = new javax.swing.JButton();
        rejButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Confirm Contact");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 0, 24));
        jLabel1.setText("Confirm Contact");

        qLabel.setText("Would you like to confirm ----------- as a contact?");

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(sod.SODApp.class).getContext().getActionMap(ContactConfirmPrompt.class, this);
        conButton.setAction(actionMap.get("Confirm")); // NOI18N
        conButton.setText("Confirm");

        rejButton.setAction(actionMap.get("Reject")); // NOI18N
        rejButton.setText("Reject");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(qLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(conButton)
                        .addGap(49, 49, 49)
                        .addComponent(rejButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(qLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(conButton)
                    .addComponent(rejButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton conButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel qLabel;
    private javax.swing.JButton rejButton;
    // End of variables declaration//GEN-END:variables

}
