/*
 * InvitationRequest.java
 * This prompt is displayed when a user is being invited to a collaboration.
 * The user may accept or decline.
 */
package sod;

import org.jdesktop.application.Action;

public class InvitationRequest extends javax.swing.JFrame {

    // Variable Declaration
    String chatIp;
    String chatName;
    Boolean priv;

    // Methods
    public InvitationRequest(String name, String i, String n, Boolean p) {
        initComponents();
        contactNameLabel.setText(name);
        chatIp = i;
        chatName = n;
        priv = p;
        this.setDefaultCloseOperation(this.DISPOSE_ON_CLOSE);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chatInvLabel = new javax.swing.JLabel();
        acceptButton = new javax.swing.JButton();
        contactNameLabel = new javax.swing.JLabel();
        declineButton = new javax.swing.JButton();

        setName("Form"); // NOI18N
        setResizable(false);

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(sod.SODApp.class).getContext().getResourceMap(InvitationRequest.class);
        chatInvLabel.setText(resourceMap.getString("chatInvLabel.text")); // NOI18N
        chatInvLabel.setName("chatInvLabel"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(sod.SODApp.class).getContext().getActionMap(InvitationRequest.class, this);
        acceptButton.setAction(actionMap.get("Accept")); // NOI18N
        acceptButton.setText(resourceMap.getString("acceptButton.text")); // NOI18N
        acceptButton.setName("acceptButton"); // NOI18N

        contactNameLabel.setText(resourceMap.getString("contactNameLabel.text")); // NOI18N
        contactNameLabel.setName("contactNameLabel"); // NOI18N

        declineButton.setAction(actionMap.get("Decline")); // NOI18N
        declineButton.setText(resourceMap.getString("declineButton.text")); // NOI18N
        declineButton.setName("declineButton"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chatInvLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contactNameLabel)
                .addGap(18, 18, 18)
                .addComponent(acceptButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(declineButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chatInvLabel)
                    .addComponent(contactNameLabel)
                    .addComponent(acceptButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(declineButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Action
    public void Accept() {
        SODApp.getApplication().joinChat(chatIp, chatName, priv);
        this.dispose();
    }

    @Action
    public void Decline() {
        this.dispose();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptButton;
    private javax.swing.JLabel chatInvLabel;
    private javax.swing.JLabel contactNameLabel;
    private javax.swing.JButton declineButton;
    // End of variables declaration//GEN-END:variables
}
